[[redirects]]
    force = true
    from = "/api/*"
    status = 200
    to = "/.netlify/functions/api/:splat"

[build]
    base='/'
    publish='applications/frontend/dist'
    command='pnpm --filter server build && pnpm --filter frontend build'

[functions]
    directory = "/applications/server/dist"

# Also put headers
[[headers]]
    for = "/*"

    [headers.values]
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"
        X-Content-Type-Options = "nosniff"
        cache-control = "public, max-age=10000, must-revalidate"